name: Node.js Setup and Deployment

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      your-input-name:
        description: 'Your input description'
        required: false
        
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install Git
        run: |
          sudo apt-get update && sudo apt-get install git
      - name: Install dependencies
        run: |
          npm install moment simple-git random jsonfile



      - name: Configure Git
        run: |
          git config --global user.name "fahri1616"
          git config --global user.email "ClearenceLaposky101899@outlook.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git


      - name: Run Node.js script
        run: |
          node index.js

      - name: Push changes
        run: |
          git push -f origin main
